# Generated by Django 3.2.2 on 2021-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/home/')),
                ('descricion', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
        ),
    ]
