# Generated by Django 3.2.2 on 2021-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='caico', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='complement',
            field=models.CharField(blank=True, max_length=250, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='seila', max_length=150, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='12457', max_length=100, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='849975', max_length=100, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='maria joaquina', max_length=250, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
