# Generated by Django 3.2.2 on 2021-06-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210602_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technical_information',
        ),
    ]
